/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedResultsIdRouteImport } from './routes/_authenticated/results.$id'
import { Route as AuthenticatedAssessmentsSlugRouteImport } from './routes/_authenticated/assessments.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsIdRoute = AuthenticatedResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsSlugRoute =
  AuthenticatedAssessmentsSlugRouteImport.update({
    id: '/assessments/$slug',
    path: '/assessments/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/assessments/$slug': typeof AuthenticatedAssessmentsSlugRoute
  '/results/$id': typeof AuthenticatedResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/assessments/$slug': typeof AuthenticatedAssessmentsSlugRoute
  '/results/$id': typeof AuthenticatedResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/assessments/$slug': typeof AuthenticatedAssessmentsSlugRoute
  '/_authenticated/results/$id': typeof AuthenticatedResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/recommendations'
    | '/roadmap'
    | '/assessments/$slug'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/recommendations'
    | '/roadmap'
    | '/assessments/$slug'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/recommendations'
    | '/_authenticated/roadmap'
    | '/_authenticated/assessments/$slug'
    | '/_authenticated/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$id': {
      id: '/_authenticated/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof AuthenticatedResultsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/$slug': {
      id: '/_authenticated/assessments/$slug'
      path: '/assessments/$slug'
      fullPath: '/assessments/$slug'
      preLoaderRoute: typeof AuthenticatedAssessmentsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedAssessmentsSlugRoute: typeof AuthenticatedAssessmentsSlugRoute
  AuthenticatedResultsIdRoute: typeof AuthenticatedResultsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedAssessmentsSlugRoute: AuthenticatedAssessmentsSlugRoute,
  AuthenticatedResultsIdRoute: AuthenticatedResultsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
